# Generated by Django 4.0.1 on 2023-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=255)),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
