# Generated by Django 4.0.1 on 2023-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name_plural': 'Detection'},
        ),
        migrations.AddField(
            model_name='detection',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
