# Generated by Django 3.2.16 on 2023-03-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_detection_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='room_member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.roommember'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='etat',
            field=models.CharField(default='absent', max_length=100),
        ),
    ]
