# Generated by Django 3.2.16 on 2023-03-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230329_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='room_member',
        ),
    ]
