# Generated by Django 3.2.16 on 2023-03-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_etudiant_room_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.etudiant'),
        ),
    ]
