# Generated by Django 3.2.16 on 2023-03-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_detection_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='room',
            field=models.ForeignKey(default='GRAPHE', on_delete=django.db.models.deletion.CASCADE, to='base.roommember'),
        ),
    ]
