# Generated by Django 3.2.16 on 2023-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_detection_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savemember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_member', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Savemember',
            },
        ),
    ]
