# Generated by Django 3.2.16 on 2023-03-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_savemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='etat',
        ),
    ]
