# Generated by Django 3.2.16 on 2023-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_detection_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='etat',
            field=models.CharField(default='absent', max_length=100),
        ),
    ]
