# Generated by Django 3.2.16 on 2023-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_etudiant_etat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savemember',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='etat',
            field=models.CharField(default='absent(e)', max_length=100),
        ),
    ]
