# Generated by Django 3.2.16 on 2023-04-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20230402_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(default='absent(e)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'session',
            },
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name_plural': 'etudiants'},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='etat',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.session'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.session'),
        ),
    ]
