# Generated by Django 3.2.16 on 2023-04-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_etudiant_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'sessions'},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='id',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.etudiant'),
        ),
    ]
